# Generated code do not commit.
file(TO_CMAKE_PATH "/home/steve/.cache/flutter_sdk" FLUTTER_ROOT)
file(TO_CMAKE_PATH "/home/steve/git/vorsorgereminder" PROJECT_DIR)

set(FLUTTER_VERSION "0.7.0+10" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 7 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 0 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 10 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=/home/steve/.cache/flutter_sdk"
  "PROJECT_DIR=/home/steve/git/vorsorgereminder"
  "DART_DEFINES=RkxVVFRFUl9CVUlMRF9OQU1FPTAuNy4w,RkxVVFRFUl9CVUlMRF9OVU1CRVI9MTA=,RkxVVFRFUl9WRVJTSU9OPTMuNDcuNQ==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NmExOWNjYTU2NA==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049YWY3ZTc5NmUxNg==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMy40,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=/home/steve/git/vorsorgereminder/.dart_tool/package_config.json"
  "FLUTTER_TARGET=/tmp/flutter_tools.WXYTPB/flutter_test_listener.RTCVAG/listener.dart"
)
